#!/bin/bash

code_init(){

    FILENAME="${1}_Solution_${2}"
    EXTENCTION=".cpp"

TEMPLATE_CODE="
// @uthor - Puneet
#include <bits/stdc++.h>
#define int long long
#define pb push_back
#define fi first
#define se second
#define MAX 1000003
#define MOD 1000000007
#define fastIO ios_base::sync_with_stdio(0),cin.tie(0),cout.tie(0)
using namespace std;

void solve() {

    long t;
    cin>>t;

    while(t-->0) {

    }
}

int32_t main(){

    fastIO;
    // solve();
}"

    echo "$TEMPLATE_CODE" > "${FILENAME}${EXTENCTION}"
}

CONTEST_NAME=$1
TOTAL_FILES=$2

mkdir "$CONTEST_NAME"
cd "$CONTEST_NAME" || exit

for i in $(seq 1 "$TOTAL_FILES"); do
  code_init "$CONTEST_NAME" "$i"
  done

